-- =====================================================================
--  001 — Schéma initial
--  Source : filmbox.sql (séance 1)
-- =====================================================================

CREATE TABLE sagas (
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom  VARCHAR(60) NOT NULL UNIQUE
);

CREATE TABLE films (
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titre              VARCHAR(120) NOT NULL,
    annee              INTEGER      NOT NULL CHECK (annee BETWEEN 1888 AND 2100),
    genre              VARCHAR(30)  NOT NULL,
    saga_id            INTEGER REFERENCES sagas(id),
    film_precedent_id  INTEGER REFERENCES films(id)     -- épisode précédent dans la saga
);

CREATE TABLE personnes (
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom  VARCHAR(80) NOT NULL UNIQUE
);

CREATE TABLE casting (
    film_id     INTEGER NOT NULL REFERENCES films(id),
    personne_id INTEGER NOT NULL REFERENCES personnes(id),
    role        VARCHAR(12) NOT NULL CHECK (role IN ('acteur', 'realisateur')),
    PRIMARY KEY (film_id, personne_id, role)
);

CREATE TABLE utilisateurs (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pseudo      VARCHAR(30) NOT NULL UNIQUE,
    ville       VARCHAR(50),
    inscrit_le  DATE NOT NULL
);

CREATE TABLE notes (
    utilisateur_id INTEGER NOT NULL REFERENCES utilisateurs(id),
    film_id        INTEGER NOT NULL REFERENCES films(id),
    note           NUMERIC(2,1) NOT NULL CHECK (note BETWEEN 0.5 AND 5),
    note_le        DATE NOT NULL,
    PRIMARY KEY (utilisateur_id, film_id)                -- une note par membre et par film
);

CREATE TABLE journal (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    utilisateur_id  INTEGER NOT NULL REFERENCES utilisateurs(id),
    film_id         INTEGER NOT NULL REFERENCES films(id),
    date_visionnage DATE    NOT NULL
);
